CREATE DATABASE bankDB;
USE bankDB;
CREATE TABLE bank_info(
id INT AUTO_INCREMENT PRIMARY KEY,
account_holder VARCHAR(20) NOT NULL UNIQUE,
pin CHAR(4) NOT NULL,
balance DECIMAL(15,2) NOT NULL DEFAULT 0.00,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
INSERT INTO bank_info(account_holder,pin,balance) VALUES
("Kavya Mathiyalagan",2005,20000);
SELECT * FROM bank_info;